export const SAT_IMPORT_HEADERS = [
  "question_id",
  "section",
  "domain",
  "skill",
  "difficulty",
  "content_set_id",
  "passage_title",
  "passage_text",
  "stimulus_image",
  "question_text",
  "question_type",
  "option_a",
  "option_b",
  "option_c",
  "option_d",
  "correct_answer",
  "answer_explanation",
  "calculator_allowed",
  "estimated_time",
  "tags",
  "status",
  "content_origin",
  "author",
  "license",
  "source_reference",
  "created_by_ai",
] as const;

export const TOEFL_IMPORT_HEADERS = [
  "question_id",
  "section",
  "content_set_id",
  "passage_title",
  "passage_text",
  "audio_url",
  "audio_transcript",
  "question_type",
  "question_text",
  "option_a",
  "option_b",
  "option_c",
  "option_d",
  "correct_answer",
  "answer_explanation",
  "difficulty",
  "skill",
  "estimated_time",
  "tags",
  "status",
  "content_origin",
  "author",
  "license",
  "source_reference",
  "created_by_ai",
] as const;

function toCsvLine(values: readonly string[]): string {
  return values
    .map((v) => (v.includes(",") || v.includes('"') || v.includes("\n") ? `"${v.replace(/"/g, '""')}"` : v))
    .join(",");
}

export function generateSatImportTemplate(): string {
  const example = [
    "SAT-RW-000001",
    "READING_WRITING",
    "Information and Ideas",
    "Central Ideas and Details",
    "MEDIUM",
    "",
    "",
    "",
    "",
    "Which choice best states the main idea of the passage?",
    "MULTIPLE_CHOICE",
    "It describes a historical event.",
    "It argues for a policy change.",
    "It explains a scientific process.",
    "It profiles a public figure.",
    "A",
    "The passage is structured around a single historical event.",
    "",
    "75",
    "main-idea",
    "DRAFT",
    "ORIGINAL_SMARTPREP_QUESTION",
    "",
    "",
    "",
    "false",
  ];
  return `${SAT_IMPORT_HEADERS.join(",")}\n${toCsvLine(example)}\n`;
}

export function generateToeflImportTemplate(): string {
  const example = [
    "TOEFL-R-001-Q1",
    "READING",
    "TOEFL-R-001",
    "The History of Glass",
    "Glass has been manufactured for thousands of years...",
    "",
    "",
    "MULTIPLE_CHOICE",
    "According to paragraph 1, glass was first manufactured...",
    "In ancient Egypt",
    "In ancient Rome",
    "In ancient China",
    "In ancient Greece",
    "A",
    "Paragraph 1 states glass manufacturing began in ancient Egypt.",
    "MEDIUM",
    "Detail",
    "90",
    "history",
    "DRAFT",
    "ORIGINAL_SMARTPREP_QUESTION",
    "",
    "",
    "",
    "false",
  ];
  return `${TOEFL_IMPORT_HEADERS.join(",")}\n${toCsvLine(example)}\n`;
}
